//construct-plymouth script file

window_width = Window.GetWidth();
window_height = Window.GetHeight();
origin_x = Window.GetX();
origin_y = Window.GetY();

background_col = 19/255;
Window.SetBackgroundTopColor(0, background_col, background_col);
Window.SetBackgroundBottomColor(0, background_col, background_col);

background_image = Image("background.png");
background_sprite = Sprite(background_image);
background_sprite.SetPosition(origin_x, origin_y, 0);